HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/Administrator/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Models;
using Client_Api;

namespace HospitalManagmentSystemClient.Controllers.Administrator
{
    public class AdministratorController : Controller
    {
        ErrorModel error = new ErrorModel();
        public ActionResult Index(int? id)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            //id = 6003;
            if (id != null)
            {
                System.Web.HttpContext.Current.Session.Add("key", "admin");
                System.Web.HttpContext.Current.Session.Add("UserId", id);
                Login_Api la = new Login_Api();
                var name = la.GetUserName(id);

                System.Web.HttpContext.Current.Session.Add("UserName", name);

            }

            return View("~/Views/Administrator/AdministratorHome.cshtml");
        }

        public ActionResult ViewPatients()
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminGetAllPatientsApi = new Admin_Api();
            var model = adminGetAllPatientsApi.GetAllPatients();
            if (model != null) {
                return View("~/Views/Administrator/AdminViewPatients.cshtml", model);
            }
            error.ErrorMessage = "Unable to Get Patient Details";
            return View("~/Views/Error.cshtml", error);
        }

        [HttpPost]
        public ActionResult ManagePatients(PatientModel patientUpdates)
        {
           if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminGetAllPatients = new Admin_Api();
            var model = adminGetAllPatients.UpdatePatient(patientUpdates);

            if (model != null)
            {
                return View("~/Views/Administrator/AdminViewPatients.cshtml", model);
            }
            return View("~/Views/Error.cshtml");
        }

        public ActionResult ViewDoctors()
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminGetAllDoctorsApi = new Admin_Api();

            var model = adminGetAllDoctorsApi.GetAllDoctor();

            if (model != null) {

                return View("~/Views/Administrator/AdminViewDoctors.cshtml", model);
            }

            return View("~/Views/Error.cshtml");
        }

        [HttpPost]
        public ActionResult ManageDoctors(DoctorModel doctorUpdates)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();

            var model = adminApi.UpdateDoctor(doctorUpdates);
            if (model != null)
            {
                return View("~/Views/Administrator/AdminViewDoctors.cshtml", model);
            }
            //ErrorModel.ErrorMessage = "Unable to fetch patient Details Please Again later";
            return View("~/Views/Error.cshtml");

        }


        public ActionResult ViewNurses()
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminGetAllDoctorsApi = new Admin_Api();

            var model = adminGetAllDoctorsApi.GetAllNurses();

            if (model != null)
            {

                return View("~/Views/Administrator/AdminViewNurses.cshtml", model);
            }

            return View("~/Views/Error.cshtml");
        }

        public ActionResult ManageNurses(NurseModel nurseUpdates)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();

            var model = adminApi.UpdateNurse(nurseUpdates);
            if (model != null)
            {
                return View("~/Views/Administrator/AdminViewNurses.cshtml", model);
            }
            return View("~/Views/Error.cshtml");
        }

        public ActionResult ViewLabIncharges()
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminGetAllDoctorsApi = new Admin_Api();

            var model = adminGetAllDoctorsApi.GetAllLabIncharges();

            if (model != null)
            {

                return View("~/Views/Administrator/AdminViewLabIncharges.cshtml", model);
            }

            return View("~/Views/Error.cshtml");
        }

        public ActionResult ManageLabIncharges(LabInchargeModel inchargeUpdates)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();

            var model = adminApi.UpdateIncharges(inchargeUpdates);
            if (model != null)
            {
                return View("~/Views/Administrator/AdminViewLabIncharges.cshtml", model);
            }
            //ErrorModel.ErrorMessage = "Unable to fetch patient Details Please Again later";
            return View("~/Views/Error.cshtml");

        }


        #region Notifications

        public ActionResult ManageNotification(NotificationsModel mangeNotifications)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();

            mangeNotifications.AdminID = (int)Session["UserId"]; //6003;
            var notificationsModels = adminApi.ManageNotifications(mangeNotifications);
            return View("~/Views/Administrator/AdminManageNotifications.cshtml", notificationsModels);
        }

        public ActionResult SaveNotification(NotificationsModel mangeNotifications)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();
            IEnumerable<NotificationsModel> notificationsModels = null;
            if (!mangeNotifications.Expiry.Equals("1/1/0001 12:00:00 AM"))
            {
                mangeNotifications.AdminID = (int)Session["UserId"];
                mangeNotifications.Created_DateTime = DateTime.Now;
                notificationsModels = adminApi.InsertNotifications(mangeNotifications);
            }
            return View("~/Views/Administrator/AdminManageNotifications.cshtml", notificationsModels);
        }

        public ActionResult GetAllNotifications(NotificationsModel getNotifications)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();
            getNotifications.AdminID = (int)System.Web.HttpContext.Current.Session["UserId"]; //6003;
            var notificationsModels = adminApi.GetAllNotifications(getNotifications);
            return View("~/Views/Administrator/AdminManageNotifications.cshtml", notificationsModels);
        }

        public ActionResult NewNotification()
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            return View("~/Views/Administrator/AdminAddNotifications.cshtml");
        }

        [HttpPost]
        public ActionResult GetRoleDetails(NotificationsModel notification)
        {
            if (Convert.ToString(Session["key"]) != "admin") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();
            NotificationsModel model = new NotificationsModel();
            ViewBag.dropdownModel = null;

            if (notification.Notifications.Equals("Doctors"))
            {

                var persons = adminApi.GetAllDoctor();
                foreach (var p in persons)
                {
                    model.personDetails.Add(new SelectListItem {
                        Text = p.firstName,
                        Value = Convert.ToString(p.pid)
                    });
                }
                ViewBag.dropdownModel = "Doctors";
            }
            else if (notification.Notifications.Equals("Patients"))
            {
                var persons = adminApi.GetAllPatients();
                foreach (var p in persons)
                {
                    model.personDetails.Add(new SelectListItem
                    {
                        Text = p.firstName,
                        Value = Convert.ToString(p.pid)
                    });
                }
                ViewBag.dropdownModel = "Patients";

            }
            else if (notification.Notifications.Equals("Nurses"))
            {
                var persons = adminApi.GetAllNurses();
                foreach (var p in persons)
                {
                    model.personDetails.Add(new SelectListItem
                    {
                        Text = p.firstName,
                        Value = Convert.ToString(p.pid)
                    });
                }
                ViewBag.dropdownModel = "Nurses";
            }
            else if (notification.Notifications.Equals("LabIncharges"))
            {
                var persons = adminApi.GetAllLabIncharges();
                foreach (var p in persons)
                {
                    model.personDetails.Add(new SelectListItem
                    {
                        Text = p.firstName,
                        Value = Convert.ToString(p.pid)
                    });
                }
                ViewBag.dropdownModel = "LabIncharges";
            }

            return View("~/Views/Administrator/AdminAddNotifications.cshtml", model);
        }

        public ActionResult ViewRoleNoti(string role)
        {
            if (role != null && role != "-Select")
            {

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/Nurse/NurseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Client_Api;
using Models;


namespace HospitalManagmentSystemClient.Controllers.Nurse
{
    public class NurseController : Controller
    {
        // GET: Nurse
        public ActionResult Index(int? id)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");
            if (id != null)
            {
                System.Web.HttpContext.Current.Session.Add("key", "nurse");
                System.Web.HttpContext.Current.Session.Add("UserId", id);
                Login_Api la = new Login_Api();
                var name = la.GetUserName(id);

                System.Web.HttpContext.Current.Session.Add("UserName", name);
            }
            Admin_Api adminApi = new Admin_Api();
            NotificationsModel notificationModel = new NotificationsModel();
            notificationModel.UserRoleID = (int)Session["UserId"]; //6003
            var notifications = adminApi.GetAllNotificationsByRole(notificationModel);
            return View("~/Views/Nurse/NurseHome.cshtml", notifications);
        }

        public ActionResult SelectDoctors()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

           AppointmentModel doctorApts = new AppointmentModel();

            Admin_Api adminApi = new Admin_Api();
            var docs = adminApi.GetAllDoctor();

            foreach (var d in docs)
            {
                doctorApts.dropDown.Add(new SelectListItem
                    { Text = d.firstName,
                Value =Convert.ToString(d.pid)});
            }

            return View("~/Views/Nurse/ViewDoctorsList.cshtml", doctorApts);
        } 


        public ActionResult ViewDoctorAppointments(AppointmentModel person)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            Doctor_Api doctorApi = new Doctor_Api();
            if (person.doctor_ID != 0)
            {
                var doctorApmnts = doctorApi.GetDocApntment_Api(person.doctor_ID).Where(a => (a.cancelled == false && a.appointment_Date > DateTime.Now));
                return View("~/Views/Nurse/NurseViewDoctorAppointments.cshtml", doctorApmnts);
            }
            else
            {
                AppointmentModel doctorApts = new AppointmentModel();

                Admin_Api adminApi = new Admin_Api();
                var docs = adminApi.GetAllDoctor();

                foreach (var d in docs)
                {
                    doctorApts.dropDown.Add(new SelectListItem
                    {
                        Text = d.firstName,
                        Value = Convert.ToString(d.pid)
                    });
                }

                return View("~/Views/Nurse/ViewDoctorsList.cshtml", doctorApts);
            }
          }


        public ActionResult SelectPatients()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();
            var pats = adminApi.GetAllPatients();
            AppointmentModel docapts = new AppointmentModel();

            foreach (var d in pats)
            {
                docapts.dropDown.Add(new SelectListItem
                {
                    Text = d.firstName,
                    Value = Convert.ToString(d.pid)
                });
            }

            return View("~/Views/Nurse/ViewPatientList.cshtml", docapts);
        }

        public ActionResult ViewPatientAppointments(AppointmentModel person)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");
            Patient_Api patientApi = new Patient_Api();
            var patientApmnts = patientApi.GetAppointments(person.paitent_ID).Where(a => (a.cancelled == false && a.appointment_Date > DateTime.Now));
            return View("~/Views/Nurse/NurseViewPatientAppointments.cshtml", patientApmnts);
        }


        public ActionResult ViewRooms()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            TreatmentRoom_Api roomApi = new TreatmentRoom_Api();
            var model = roomApi.GetAllTreatmentRooms();

            Patient_Api patientApi = new Patient_Api();
            var p = patientApi.GetPaitentsList();

            foreach (var m in model)
            {
                m.patientList = p;
            }

            return View("~/Views/Nurse/NurseViewRooms.cshtml", model);
        }
    }
}

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/NurseHome.cshtml
@{
    ViewBag.Title = "NurseHome";
}

<h2>NurseHome</h2>


@model IEnumerable<Models.NotificationsModel>

@if (Model != null)
{
    <div>
        @Html.Partial("_NotificationHome", Model)
    </div>
}

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/NurseViewDoctorAppointments.cshtml
@model IEnumerable<Models.AppointmentModel>
@{
    ViewBag.Title = "NurseViewDoctorAppointments";
}

@section ContentBreadCrumBar
    {
    <a class="glyphicon"> Nurse View Doctor Appointments</a>
}
<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">


    </script>
</head>
<body>

                    <table id="detailsTable">
                        <thead>
                            <tr>
                                <th>Appointment Number</th>
                                <th>Patient Name </th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                            </tr>
                        </thead>
                        @foreach (var apmnt in Model)
                        {
                            <tr style="text-align:center">
                                <td>
                                    @apmnt.appointment_ID
                                </td>
                                <td>
                                    @apmnt.patientName
                                </td>
                                <td>
                                    @((apmnt.appointment_Date).ToShortDateString())
                                </td>
                                <td>
                                    @apmnt.timings
                                </td>
                            </tr>
                        }
                    </table>

  

</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/NurseViewPatientAppointments.cshtml
@model IEnumerable<Models.AppointmentModel>
@{
    ViewBag.Title = "NurseViewPatientAppointments";
}
@section ContentBreadCrumBar
    {
    <a class="glyphicon "> Nurse View Patient Appointments </a>
}
<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

    </script>
</head>
<body>

              <table id="detailsTable">
                        <thead>
                            <tr>
                                <th>Appointment Number</th>
                                <th>Doctor ID </th>
                                <th>Patient ID</th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                         {
                            <tr style="text-align:center">
                                <td>
                                    @item.appointment_ID
                                </td>
                                <td>
                                    @item.doctorName
                                </td>
                                <td>
                                    @item.patientName
                                </td>
                                <td>
                                    @((item.appointment_Date).ToString("MM-dd-yyyy"))
                                </td>
                                <td>
                                    @(item.timings)
                                </td>
                            </tr>
                        }
                    </table>


</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/NurseViewRooms.cshtml
@{
    ViewBag.Title = "NurseViewRooms";
    var grid = new WebGrid(Model);
}

<h2>NurseViewRooms</h2>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="karthik" content="">
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />

    <script>


        function editDoctorDetails() {
            var x = document.getElementById("editDoctorDetails");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        $(function () {
            $('.edit-mode').hide();

            $('.edit-user, .cancel-user').on('click', function () {
                var tr = $(this).parents('tr:first');
                tr.find('.edit-mode, .display-mode').toggle();
            });


            @*$('.save-user').on('click', function () {
                var tr = $(this).parents('tr:first');
                var RoomID = tr.find("#lblRoomID").html();
                var PatientID = tr.find("#lblPatientID").html();
                var Timing = tr.find("#lblTimings").html();
                var Date = tr.find("#lblDate").html();
                var IsBooked = tr.find("#isBooked").find(":selected").text();
                 //if(IsBooked)

                var roomModel =
                    {
                        "room_ID": RoomID,
                        "patient_ID": PatientID,
                        "isBooked": IsBooked,
                        "date": Date,
                        "timings": Timing
                    };
                $.ajax({
                    url: '/Administrator/UpdateRooms',
                    data: JSON.stringify(roomModel),
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    success: function () {
                        location.reload();
                        //$.get('@Url.Action("ViewRooms", "Administrator")', {}, function () { })
                    }
                });
            });*@

            $('.edit-user').on('click', function () {

            });

        })
    </script>
    <style type="text/css">
        .edit-mode {
            width: 100%;
        }

        .edit-user {
            width: 100%;
        }

            .edit-user display-mode {
                width: 100%;
            }

        .save-user edit-mode {
            width: 100%;
        }

        .display-mode {
            width: 100%;
        }

        .cancel-user {
            width: 100%;
        }

        .webgrid-table {
            font-family: Arial,Helvetica,sans-serif;
            font-size: 14px;
            font-weight: normal;
            width: 110%;
            display: table;
            border-collapse: collapse;
            border: solid #C5C5C5;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #C5C5C5;
                padding: 3px 7px 2px;
                /*width: 100%;*/
            }

        .webgrid-header, .webgrid-header a {
            background-color: #0094ff;
            color: #ffffff;
            text-align: left;
            text-decoration: none;
        }

        .webgrid-footer {
        }

        .webgrid-row-style {
            padding: 3px 7px 2px;
        }

        .webgrid-alternating-row {
            background-color: azure;
            padding: 3px 7px 2px;
        }

        .col1Width {
            width: 55px;
        }

        .col2Width {
            width: 220px;
        }
    </style>
</head>

<body>

    @section ContentBreadCrumBar
    {
        <a class="glyphicon glyphicon-home"> Nurse View Room Details</a>
    }


    <div id="gridContent" style=" padding:20px; ">
        @grid.GetHtml(
        tableStyle: "webgrid-table",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        mode: WebGridPagerModes.All,
        columns:
            grid.Columns(

             grid.Column("RoomID", format: @<text>  <span class="display-mode"><label id="lblRoomID">@item.room_ID</label></span><label id="RoomID" class="edit-mode">@item.room_ID </label></text>, style: "col2Width"),

             grid.Column("Patient Name", format:@<text>  <span class="display-mode"> <label id="lblPatientID">@item.patientFirstName</label> </span><label class="edit-mode">@item.patientFirstName</label> </text>, style: "col2Width"),

              grid.Column("Timing", format: @<text>  <span class="display-mode"><label id="lblTimings">@((DateTime.Parse(item.timings)).ToString("HH:mm"))</label> </span><label class="edit-mode">@((DateTime.Parse(item.timings)).ToString("HH:mm"))</label> </text>, style: "col2Width"),

             grid.Column("Date", format:@<text>  <span class="display-mode"><label id="lblDate">@((item.date).ToString("MM-dd-yyyy"))</label></span><label class="edit-mode">@((item.date).ToString("MM-dd-yyyy"))</label> </text>, style: "col2Width"),

             grid.Column("IsBooked", format: @<text>

                    <span class="display-mode"><label id="IsBooked">@item.isBooked</label></span>
                    @if (item.isBooked)
                    {
                        <select id="isBooked" class="edit-mode" value="@item.isBooked">
                            <option value="true">True</option>
                            <option value="false">False</option>
                        </select>
                    }

            </text>, style: "col1Width")

             @*grid.Column("Action", format: @<text>
                    <button class="edit-user display-mode">Edit</button>
                    <form method="post" action="@Url.Action("UpdateRooms", "Administrator", new { roomID = @item.room_ID})">
                        <button class="save-user edit-mode">Save</button>

                    </form>
                    <button class="cancel-user edit-mode">Cancel</button>
            </text>, style: "col1Width", canSort: false)*@
        ))
    </div>


    @*<input type="button" class="submitBtn" value="Book Room" style="" onclick="@("window.location.href='" + @Url.Action("viewNewBooking", "Administrator" ) +"'");" />*@


    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
</body>

</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/ViewDoctorsList.cshtml
@model Models.AppointmentModel
@{
    ViewBag.Title = "View Doctors List";
}


@section ContentBreadCrumBar
    {
    <a class="glyphicon ">Nurse View DoctorsList</a>
}

<table>
    <tr>
        @using (Html.BeginForm("ViewDoctorAppointments", "Nurse", FormMethod.Post, new { enctype = "multipart/form" }))
        {
            <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.doctor_ID, new SelectList(Model.dropDown, "Value", "Text"), "--Select--")</td>

            <td><input type="submit" value="Submit" /></td>
        }
    </tr>
</table>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Nurse/ViewPatientList.cshtml
@model Models.AppointmentModel
@{
    ViewBag.Title = "View Doctors List";
}

@section ContentBreadCrumBar
    {
    <a class="glyphicon ">Nurse View DoctorsList</a>
}

<table>
    <tr>
        @using (Html.BeginForm("ViewPatientAppointments", "Nurse", FormMethod.Post, new { enctype = "multipart/form" }))
        {
            <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.paitent_ID, new SelectList(Model.dropDown, "Value", "Text"), "--Select--")</td>

            <td><input type="submit" value="Submit" /></td>
        }
    </tr>
</table>