HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/Patient/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Client_Api;
using Models;

namespace HospitalManagmentSystemClient.Controllers.Patient
{
    [DoctorActionFiler]
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index(int? id)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");
           // id = 7001;

            if (id != null)
            {
                System.Web.HttpContext.Current.Session.Add("key", "patient");
                System.Web.HttpContext.Current.Session.Add("UserId", id);
                Login_Api la = new Login_Api();
                var name = la.GetUserName(id);

                System.Web.HttpContext.Current.Session.Add("UserName", name);
            }
            Admin_Api adminApi = new Admin_Api();
            NotificationsModel notificationModel = new NotificationsModel();
            notificationModel.UserRoleID = (int)Session["UserId"]; //6003
            var notifications =  adminApi.GetAllNotificationsByRole(notificationModel);

            return View("~/Views/Patient/PatientHome.cshtml", notifications);
        }

        //view  screen
        public ActionResult PatientAppointment(int patientId = 0)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            AppointmentModel appModel = new AppointmentModel();
            Admin_Api adminApi = new Admin_Api();
            var model = adminApi.GetAllDoctor().ToArray();

            List<DoctorDropDown> items = new List<DoctorDropDown>();

            foreach (var m in model)
            {
                appModel.doctorDetails.Add(m);
                items.Add(new DoctorDropDown
                {
                    Value = (m.pid),
                    Text = m.firstName
                });
            }
            appModel.doctorDropDown = items;

            return View("~/Views/Patient/PatientBookAppointment.cshtml", appModel);
        }

        //ViewAppointments
        [HttpGet]
        public ActionResult GetAppointments(int? patientID = 0)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            int id = (int)Session["UserId"];
            Patient_Api patientApi = new Patient_Api();

            IEnumerable<AppointmentModel> patientAppointments = patientApi.GetAppointments(id).Where(a => a.cancelled == false);

            foreach (var p in patientAppointments)
            {
                if (p.appointment_Date > DateTime.Now) {
                    p.canCancel = true;
                        }
            }

            if (patientAppointments != null)
            {
                return View("~/Views/Patient/PatientViewAppointments.cshtml", patientAppointments);
            }

            return View("~Views/Error.cshtml");
        }

        [HttpPost]
        public ActionResult GetAvailableTimings(AppointmentModel apmtModel)
        {
            Doctor_Api doctorApi = new Doctor_Api();
            apmtModel.appointment_Date = DateTime.Parse(apmtModel.timings);
            apmtModel.paitent_ID = (int)Session["UserId"];
            List<string> bookedTimings = doctorApi.GetAvailableTimings(apmtModel);

            AppointmentTimings appTimings = new AppointmentTimings();
            List<timingsValues> timings = appTimings.timingsDropDown;

            int id = (int)Session["UserId"];
            Patient_Api patientApi = new Patient_Api();

            IEnumerable<AppointmentModel> patientAppointments = patientApi.GetAppointments(id);

            List<timingsValues> displayTimings = new List<timingsValues>();
            if (bookedTimings.Count ==0)
            {
                var app = patientAppointments.Where(a => a.appointment_Date == apmtModel.appointment_Date).Select(t => t.timings).ToList();
                if (app.Count() > 0)
                {
                    List<timingsValues> t = new List<timingsValues>();
                    foreach (var a in app)
                    {
                        var aa = a.Trim('0');
                        t.Add(new timingsValues { Text= aa.Trim(':'), Value= aa.Trim(':')});
                    }
                    var i = 0;
                    foreach (var val in t)
                    {
                        displayTimings = timings.Where(d => d.Text != t.ElementAt(i).Text).ToList();
                        i++;
                    }
                }
                else
                displayTimings = timings;//.Where(t => !bookedTimings.Contains(t.Value)).ToList();

            }
            if (bookedTimings.Count != 0)
            {
                displayTimings.Add(new timingsValues { Value = "00:00", Text = "00:00" });
            }
            return Json(displayTimings, JsonRequestBehavior.AllowGet);
        }

       public ActionResult ViewEditAppointment(int id)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            AppointmentModel appModel = new AppointmentModel();
            appModel.appointment_ID = id;
            Admin_Api adminApi = new Admin_Api();
            var model =  adminApi.GetAllDoctor().ToArray();

            List<DoctorDropDown> items = new List<DoctorDropDown>();

            foreach (var m in model) {
                appModel.doctorDetails.Add(m);
                items.Add(new DoctorDropDown
                {
                    Value = (m.pid),
                    Text = m.firstName
                });
            }
            appModel.doctorDropDown = items;

            return View("~/Views/Patient/PatientEditAppointment.cshtml", appModel);
        }


        public ActionResult EditAppointment(AppointmentModel appModel)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");
            Appointment_Api apmtApi = new Appointment_Api();

           apmtApi.UpdateApnmt_Api(appModel);

            return Json("success", JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteAppointment(AppointmentModel appModel)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");
            Appointment_Api apmtApi = new Appointment_Api();

            appModel.paitent_ID = (int)Session["UserId"];
            apmtApi.DeleteApnmt_Api(appModel);

            return Json("success", JsonRequestBehavior.AllowGet);
        }

        //post data for booking
        public ActionResult PatientBookAppointment(AppointmentModel patientAppointment)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            Patient_Api patientApi = new Patient_Api();

            patientAppointment.paitent_ID = (int)Session["UserId"];
            patientAppointment.date = DateTime.Now;
           AppointmentModel model = patientApi.PatientBookAppointment(patientAppointment);


            if (model.appointment_ID != 0)
            {
               return View("~/Views/Patient/SuccessBooking.cshtml", model);
            }

            return View("~/Views/Error.cshtml");
        }

        public ActionResult GetPayments()
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            Patient_Api patientApi = new Patient_Api();
            var paymentsModel =  patientApi.GetPatientPayments((int)Session["UserId"]).GroupBy(g => g.bill_ID).Select(pa => pa.First()).ToList();
            PaymentModel p = new PaymentModel();
            foreach (var pay in paymentsModel)
            {
                p.billList.Add(new SelectListItem { Text=pay.bill_ID.ToString(), Value=pay.bill_ID.ToString()});
            }
            return View("~/Views/Patient/SelectBillID.cshtml", p);
        }

        public ActionResult GetPaymentsWithBillID(PaymentModel p)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            Patient_Api patientApi = new Patient_Api();
            var paymentsModel = patientApi.GetPatientPayments((int)Session["UserId"]).Where(b => b.bill_ID == p.bill_ID);
            if (paymentsModel.Count() != 0) {
                ViewBag.totalAmount = paymentsModel.Last().total_Amount;
                ViewBag.paidAmount = paymentsModel.Last().paid_Amount ;
                double totalPaidAmount = 0;
                foreach (var pp in paymentsModel)
                {
                    totalPaidAmount = totalPaidAmount + pp.paid_Amount;
                }
                ViewBag.TotalPaid = totalPaidAmount;
                ViewBag.PendingAmount = ViewBag.totalAmount - totalPaidAmount;
            }
            else
            {
                return Redirect("PayPayments");
            }
            return View("~/Views/Patient/PayPayments.cshtml", paymentsModel);
        }

        public ActionResult GetPaymentsWithID(int id)
        {
            if (Convert.ToString(Session["key"]) != "patient") return RedirectToAction("Login", "Home");

            Patient_Api patientApi = new Patient_Api();

            Account_Api accApi = new Account_Api();
            AccountModel accModel = new AccountModel();
            accModel.patient_ID = (int)Session["UserId"];
            var model = accApi.GetAccountsByBillID(accModel);
            var billingID = model.Where(a =>a.appointment_ID == id).FirstOrDefault();
            if (billingID != null) {
                var paymentsModel = patientApi.GetPatientPayments((int)Session["UserId"]);
                List<PaymentModel> pay = null;
                if (paymentsModel.Count() != 0)
                {

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/NoReports.cshtml
@{
    ViewBag.Title = "NoReports";
}

<h3>@ViewBag.info</h3>
 

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/PatientBookAppointment.cshtml
@model Models.AppointmentModel
@{
    ViewBag.Title = "Patient Manage Appointments";
}
@section ContentBreadCrumBar
{
    <a class="glyphicon glyphicon-home">Patient Book Appointment</a>
}

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function () {
            $j('.date-picker').datepicker({

                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 1,
                    minDate: 1,
                    maxDate: "+3Y",
                    //beforeShowDay: $..noWeekends('.date-picker'),


                    onSelect: function (dateText, instance) {
                        var d = dateText.toString();
                        var PatDocId = $('#doctorDetail').find(":selected").val();//sel.options[sel.selectedIndex].Text();

                        console.log(PatDocId);
                        var apmtModel =
                            {
                                "patient_Id": 0,
                                "timings": d,
                                "doctor_ID": PatDocId
                            };


                        $.ajax({
                            type: "POST",
                            url: "GetAvailableTimings",
                            data: JSON.stringify(apmtModel),
                            contentType: "application/json; charset=utf-8",
                           // dataType: "json",
                            success: function (data) {
                                $("#timingsDropDown").empty();
                                
                                $.each(data, function (i, obj) {
                                    if (obj.Text == "00:00") {
                                        alert("Appointment Already Booked with this Doctor, check Appointments ");
                                        return;
                                    }
                                    var p = new Option(obj.Text, obj.Value);
                                    $("#timingsDropDown").append(p);
                                });
                            }
                        });
                    }
                }

                );


        });
    </script>
    <style>
        th.ui-datepicker-week-end,
        td.ui-datepicker-week-end {
            display: none;
        }
    </style>

</head>
<body>
   

    <table id="detailsTable">
        <thead>
            <tr>
                <th>DoctorID</th>
                <th>Appointment Timings</th>
                <th>Appointment Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tr>

            @using (Html.BeginForm("PatientBookAppointment", "Patient", FormMethod.Post, new { enctype = "multipart/form" }))
            {
                <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.doctor_ID, new SelectList(Model.doctorDropDown, "Value", "Text"), "Select Doctor", new { @id = "doctorDetail" })</td>

                @*<td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.doctor_ID, new SelectList(Model.doctorIDs), "Select Doctor")</td>*@

                <td> @Html.TextBoxFor(i => i.appointment_Date,"" , new { @class="date-picker"} ) </td>

                  <td>@Html.DropDownListFor(i => i.timings, Enumerable.Empty<SelectListItem>(), "-Select Timing-", new { @id = "timingsDropDown" })</td>

                  <td><input type="submit" value="Book Appointment" /></td>
            }
            
        </tr>
    </table>

  
    
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/PatientEditAppointment.cshtml
@{
    ViewBag.Title = "Patient Edit Appointment";
}

@model Models.AppointmentModel

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function () {
            $j('.date-picker').datepicker({

                    defaultDate: "+1w",
                //defaultDate: new Date(),
                    defaultDate: new Date($(this).val().slice(-4), $(this).val().substring(0, 2), 1),//new Date('01/04/2014'),//new Date($(this ).val().slice(-4), $(this ).val().substring(0, 2), 1),
                    changeMonth: true,
                    numberOfMonths: 1,
                    minDate: 0,
                    maxDate: "+3Y",
                    startDate: new Date($(this).val().slice(-4), $(this).val().substring(0, 2), 1),



                    onSelect: function (dateText, instance) {
                        var d = dateText.toString();
                        var PatDocId = $('#doctor :selected').val();

                        console.log(PatDocId);
                        var apmtModel =
                            {
                                "patient_Id": 0,
                                "timings": d,
                                "doctor_ID": PatDocId

                            };


                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetAvailableTimings", "patient")' ,// "GetAvailableTimings",
                            data: JSON.stringify(apmtModel),
                            contentType: "application/json; charset=utf-8",
                           // dataType: "json",
                            success: function (data) {
                                $("#timingsDropDown").empty();
                                $.each(data, function (i, obj) {
                                    var p = new Option(obj.Text, obj.Value);
                                    $("#timingsDropDown").append(p);
                                });
                            }
                        });
                    }
                }

                );


        });
    </script>


</head>
<body>
    @section ContentBreadCrumBar
{
        <a class="glyphicon glyphicon-home"> Home</a>
    }

    <table id="detailsTable">
        <thead>
            <tr>
                <th>Appointment ID</th>
                <th>DoctorID</th>
                <th>Appointment Timings</th>
                <th>Appointment Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tr>

            @using (Html.BeginForm("PatientBookAppointment", "Patient", FormMethod.Post, new { enctype = "multipart/form" }))
            {
                <td> @Html.DisplayFor(i => i.appointment_ID) </td>
                <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.doctor_ID, new SelectList(Model.doctorDropDown, "Value","Text"), "Select Doctor",new { @id="doctor"})</td>

                <td> @Html.TextBoxFor(i => i.appointment_Date, "", new { @class = "date-picker" }) </td>

                <td>@Html.DropDownListFor(i => i.timings, Enumerable.Empty<SelectListItem>(), "-Select Timing-", new { @id = "timingsDropDown" })</td>

                <td><input type="submit" value="Book Appointment" /></td>
            }

        </tr>
    </table>



</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/PatientHome.cshtml
@model IEnumerable<Models.NotificationsModel>
@{
    ViewBag.Title = "PatientHome";
}

@section ContentBreadCrumBar
{
    <a class="glyphicon glyphicon-home">Patient Home</a>
}

@if (Model != null)
{
    <div>
        @Html.Partial("_NotificationHome", Model)
    </div>
}

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/PatientViewAppointments.cshtml
@{
    ViewBag.Title = "Patient View Appointments";
    var grid = new WebGrid(Model);
}

@section ContentBreadCrumBar
{
    <a class="glyphicon glyphicon-home">Patient View Appointments</a>
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="karthik" content="">
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />

    <script>

        function editPatientDetails() {
            var x = document.getElementById("editPatientDetails");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        function checkOnEdit(){
            
            var tr = $(this).parents('tr:first');

            var PatDate = tr.find("#lblAppointmentDate").html();
            console.log(PatDate);
            //var today = new Date();
            //var date = (today.getMonth() + 1) + '-' + today.getDate() + '-' + today.getFullYear();
            //var p = PatDate.slice(1)
            //if (date > p) {
            //    alert("Cannot edit Past Appointments");
            //    return;
            //}
        };

        $(function () {

            $('.edit-mode').hide();


            $('.edit-user, .cancel-user').on('click', function () {
                var tr = $(this).parents('tr:first');
                tr.find('.edit-mode, .display-mode').toggle();
            });

            $('.edit-user').on('click', function () {
                //var tr = $(this).parents('tr:first');

                //var PatDate = tr.find("#lblAppointmentDate").html();
                //var today = new Date();
                //var date = (today.getMonth() + 1) + '-' + today.getDate() + '-' + today.getFullYear();
                //var p = PatDate.slice(1)
                //if (date > p) {
                //    alert("Cannot edit Past Appointments");
                //    return;
                //}
            });

            $('.delete-user').on('click', function () {

                var tr = $(this).parents('tr:first');

                var PatAppId = tr.find("#lblAppointmentID").html();
                var PatDate = tr.find("#lblAppointmentDate").html();
                var appModel = {
                    "appointment_ID": PatAppId
                }
                var today = new Date();
                var date = (today.getMonth() + 1) + '-' + today.getDate() + '-' + today.getFullYear();
                var p =PatDate.slice(1)
                if (date > p) {
                    alert("Cannot Cancel Past Appointments");
                    return;
                }
                else {
                    $.ajax({
                        url: '/Patient/DeleteAppointment',
                        data: JSON.stringify(appModel),
                        type: 'POST',
                        contentType: 'application/json; charset=utf-8',
                        success: function () {
                            location.reload();
                        }
                    });
                }
           
            });



        })
    </script>
    <style type="text/css">
        .edit-mode {
            /*width: 100%;*/
        }

        .edit-user {
            /*width: 100%;*/
        }

            .edit-user display-mode {
                /*width: 100%;*/
            }

        .save-user edit-mode {
            /*width: 100%;*/
        }

        .display-mode {
            /*width: 100%;*/
        }

        .cancel-user {
            /*width: 100%;*/
        }

        .webgrid-table {
            font-family: Arial,Helvetica,sans-serif;
            font-size: 14px;
            font-weight: normal;
            width: 110%;
            display: table;
            border-collapse: collapse;
            border: solid px #C5C5C5;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #C5C5C5;
                padding: 3px 7px 2px;
                /*width: 100%;*/
            }

        .webgrid-header, .webgrid-header a {
            background-color: #0094ff;
            color: #ffffff;
            text-align: left;
            text-decoration: none;
        }

        .webgrid-footer {
        }

        .webgrid-row-style {
            padding: 3px 7px 2px;
        }

        .webgrid-alternating-row {
            background-color: azure;
            padding: 3px 7px 2px;
        }

      
    </style>
</head>

<body>
    <div id="gridContent" style=" padding:20px; ">
        @grid.GetHtml(
        tableStyle: "webgrid-table",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        mode: WebGridPagerModes.All,
        columns:
            grid.Columns(
             grid.Column("AppointmentID", format: @<text>
                    <span class="display-mode">@item.appointment_ID </span>
                    <label id="lblAppointmentID" class="edit-mode">@item.appointment_ID</label> </text>, style: "col1Width"),


            grid.Column("Doctor Name", format: @<text>
            <span class="display-mode">@item.doctorName </span>
            <label id="lblDoctorID" class="edit-mode">@item.doctorName</label> </text>, style: "col1Width"),

             grid.Column("AppointmentDate", format:@<text>
                    <span class="display-mode" id="apptDate">@(item.appointment_Date.ToString("MM-dd-yyyy"))</span>
                    <label id="lblAppointmentDate" class="edit-mode">@(item.appointment_Date.ToString("MM-dd-yyyy"))</label> </text>, style: "col1Width"),

             grid.Column("Appointment Time", format: @<text>
                    <span class="display-mode"><label id="lblTime">@(item.timings)</label></span>
                    <label id="AppointmentTime" value="@(item.timings)" class="edit-mode">@(item.timings) </label></text>, style: "col1Width"),


             grid.Column("Action", format: @<text>
                    <button class="edit-user display-mode">Modify</button>
                    @*ViewEditAppointment*@
                    <button class="delete-user edit-mode">Cancel Appointment</button>
                    <button class="cancel-user edit-mode">Cancel</button>
            </text>, style: "col3Width", canSort: false),

                grid.Column(columnName: "Edit", format:@<text>@if (item.canCancel) {<text>@Html.ActionLink("Edit ", "ViewEditAppointment", "patient", new { id = @item.appointment_ID }, new { @Class = "btn btn-warning ", onclick = "" })</text>} </text> , header: "Edit", style: "grid-60px"),
                        
                  grid.Column("Details", format: @<text>
                    <button class="edit-user display-mode">Details</button>
                    @Html.ActionLink("Billing ", "ViewBillsWithID", "patient", new { id = @item.appointment_ID }, new { @Class = "btn btn-warning edit-mode" })
                    @Html.ActionLink("Payments ", "GetPaymentsWithID", "patient", new { id = @item.appointment_ID }, new { @Class = "btn btn-warning edit-mode" })
                    @Html.ActionLink("Reports ", "ViewReportsWithID", "patient", new { id = @item.appointment_ID }, new { @Class = "btn btn-warning edit-mode" })
                </text>, style: "col3Width", canSort: false)

        ))
    </div>

    <input type="button" class="btn btn-info btn-block submitBtn" value="Book New Appointment" style="" onclick="@("window.location.href='" + @Url.Action("PatientAppointment", "Patient" ) +"'");" />


</body>

</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/SelectBillID.cshtml
@{
    ViewBag.Title = "Select BillID";
}

<h4>Select Bill ID</h4>

@model Models.PaymentModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="karthik" content="">
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />



    <script>

        function billID() {
            var patientID = $("#patient_ID").val();

            $.ajax({
                type: "POST",
                url: "GetAppointmentsWithNoBilling",
                data: "{ 'patientID':'" + patientID + "'}",
                contentType: "application/json; charset=utf-8",
                 dataType: "json",
                success: function (data) {
                    $("#Appointment_ID").empty();

                    $.each(data, function (i, obj) {

                        var p = new Option(obj.Text, obj.Value);
                        $("#Appointment_ID").append(p);
                    });
                }
            });


        }


    </script>

</head>
<body>

    @section ContentBreadCrumBar
    {
        <a class="glyphicon glyphicon-home"> Patient View Payments</a>
    }
    <table id="detailsTable">
        <thead>
            <tr>
                <th>BillID</th>
                <th>Action</th>
            </tr>
        </thead>
        <tr>
            @using (Html.BeginForm("GetPaymentsWithBillID", "Patient", FormMethod.Post, new { enctype = "multipart/form" }))
            {
                <td style="text-align: center">@Html.DropDownListFor(i => i.bill_ID, new SelectList(Model.billList, "Value", "Text"), "-Select-")</td>
                    <td style="text-align: center"><input type="submit" value="Select Billing" /></td>
            }
        </tr>
    </table>
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Patient/SuccessBooking.cshtml
@{
    ViewBag.Title = "SuccessBooking";
}

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
</head>
<body>
    @if (Model != null)
    {
        <h3 style="text-align:center"> New Appointment Details </h3>
        <table id="detailsTable">
            <thead>
                <tr>
                    <th>Appointment ID</th>
                    <th>Doctor ID</th>
                    <th>Patient ID </th>
                    <th>Appointment Date</th>
                    <th>Appointment Time</th>
                </tr>
            </thead>
            <tr style="text-align:center">
                <td>
                    @Model.appointment_ID
                </td>
                <td>
                    @Model.doctorName
                </td>
                <td>
                    @Model.patientName
                </td>
                <td>
                    @((Model.appointment_Date).ToString("MM-dd-yyyy"))
                </td>
                <td>
                    @Model.timings
                </td>
            </tr>
        </table>
        <br />
        <br />
        <h3 style="text-align:center"> Would you like to Email the Appointment </h3>
        <input type="button" value="Send Email" class="btn btn-info btn-block submitBtn" onclick="@("window.location.href='"+ @Url.Action("SendAppointmentEmail", "Patient" , new { appID= Model.appointment_ID }) + "'");" />

    }
    else
    {
        <br />
        <h3 style="text-align:center"> Appointment with same details already exits, check existing appointments or try booking with diffent inputs </h3>
    }
    </body>
</html>