HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/Doctor/DoctorController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Client_Api;
using Models;

namespace HospitalManagmentSystemClient.Controllers.Doctor
{
    public class DoctorController : Controller
    {

        public ActionResult Index(int? id)
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login","Home");

           // id = 5006;
            if (id != null)
            {
                System.Web.HttpContext.Current.Session.Add("key", "doctor");
                System.Web.HttpContext.Current.Session.Add("UserId", id);
                Login_Api la = new Login_Api();
                var name = la.GetUserName(id);

                System.Web.HttpContext.Current.Session.Add("UserName", name);
            }


            NotificationsModel notificationModel = new NotificationsModel();
            Admin_Api adminApi = new Admin_Api();
            notificationModel.UserRoleID = (int)Session["UserId"];//6003;
            var notifications = adminApi.GetAllNotificationsByRole(notificationModel);
            return View("~/Views/Doctor/DoctorHome.cshtml",notificationModel);
        }

        public ActionResult GetAppointments()
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            int doctor_id = (int)Session["UserId"];// 5006;
            Doctor_Api doctorApi = new Doctor_Api();
            var appointments = doctorApi.GetDocApntment_Api(doctor_id);
            //var appointments = doctorApi.GetDocApntment_Api(doctor_id);

            appointments.First().filterApps.Add(new SelectListItem { Text="-Select", Value="0"});
            appointments.First().filterApps.Add(new SelectListItem { Text="Today", Value="1"});
            appointments.First().filterApps.Add(new SelectListItem { Text="Tomorrow", Value="2"});
            appointments.First().filterApps.Add(new SelectListItem { Text="All", Value="3"});
            LabIncharge_Api lApi = new LabIncharge_Api();
            var allReports = lApi.ViewPatientReports_Api(new ReportModel());

            foreach (var a in appointments)
            {
                if (allReports.Where(r => r.appointment_ID == a.appointment_ID).FirstOrDefault() != null )
                {
                    a.reportAvailable = true;
                }
                else a.reportAvailable = false;
                if (a.appointment_Date > DateTime.Now) a.canCancel = true;
            }


            if (appointments != null)
            {
                return View("~/Views/Doctor/DoctorViewAppointments.cshtml", appointments.OrderBy(a=>a.appointment_Date));
            }
            return View("~/Views/Error.cshtml");
        }

        public ActionResult GetAppointmentsByFilter(int filterID)
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");


            int doctor_id = (int)Session["UserId"];// 5006;
            Doctor_Api doctorApi = new Doctor_Api();
            var appointments = doctorApi.GetDocApntment_Api(doctor_id);

            LabIncharge_Api lApi = new LabIncharge_Api();
            var allReports = lApi.ViewPatientReports_Api(new ReportModel());

            foreach (var a in appointments)
            {
                if (allReports.Where(r => r.appointment_ID == a.appointment_ID).FirstOrDefault() != null)
                {
                    a.reportAvailable = true;
                }
                else a.reportAvailable = false;
                int timeNow = Convert.ToInt32(DateTime.Now.Hour);
                int appTime = (Convert.ToInt32((a.timings).Substring(0, 2)));

                if (((a.appointment_Date).ToShortDateString().Equals((DateTime.Now.AddDays(1).ToShortDateString())) && (appTime > timeNow)) || (a.appointment_Date > DateTime.Now) )
                {
                    a.canCancel = true;
                }
                
            }

           

            if (filterID == 1)
            {
                appointments = appointments.Where(a => ((a.appointment_Date).ToShortDateString().Equals((DateTime.Now).ToShortDateString())));// && a.appointment_Date > DateTime.Now.AddDays(-1) && a.appointment_Date <= DateTime.Now ));

               
                appointments.First().filterApps.Add(new SelectListItem { Text = "-Select", Value = "0" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "Today", Value = "1" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "Tomorrow", Value = "2" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "All", Value = "3" });

            }
            else if (filterID == 2)
            {


                appointments = appointments.Where(a => ((a.appointment_Date).ToShortDateString().Equals(DateTime.Now.AddDays(1).ToShortDateString())));// && a.appointment_Date > DateTime.Now));

               

                appointments.First().filterApps.Add(new SelectListItem { Text = "-Select", Value = "0" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "Today", Value = "1" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "Tomorrow", Value = "2" });
                appointments.First().filterApps.Add(new SelectListItem { Text = "All", Value = "3" });

            }
            //else if (id == 3)
            //{

            //}
            if (filterID == 3 || filterID ==0)
            {
                return RedirectToAction("GetAppointments");
            }

            if (appointments != null)
            {
                return View("~/Views/Doctor/DoctorViewAppointments.cshtml", appointments.OrderBy(a => a.appointment_Date));
            }
            return View("~/Views/Error.cshtml");
        }



        public ActionResult ViewAppointmentsToCancel()
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            int doctor_id = (int)Session["UserId"];// 5006;
            Doctor_Api doctorApi = new Doctor_Api();
            var appointments = doctorApi.GetDocApntment_Api(doctor_id);

            if (appointments != null)
            {
                return View("~/Views/Doctor/DoctorCancelAppts.cshtml", appointments);
            }
            return View("~/Views/Error.cshtml");
        }


        public ActionResult GetAppointmentsByDate(DateTime test)
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            int doctor_id = (int)Session["UserId"];// 5006;
            Doctor_Api doctorApi = new Doctor_Api();
            var appointments = doctorApi.GetDocApntment_Api(doctor_id).Where(a =>a.appointment_Date == test);

            //ViewBag.appts = appointments.Select(a => a.appointment_ID);
            TempData["Date"] = test;
            if (appointments != null)
            {
                return View("~/Views/Doctor/DoctorCancelAppts.cshtml", appointments);
            }
            return View("~/Views/Error.cshtml");
        }

        public ActionResult cancelAppointment(int id)
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            Doctor_Api doctorApi = new Doctor_Api();
            AppointmentModel app = new AppointmentModel();
            app.appointment_ID = id;
            app.doctor_ID = (int)Session["UserId"];
            var appointments = doctorApi.cancelAppointment(app);
            EmailsController email = new EmailsController();
            email.EmailCancelledAppt(app);

            return RedirectToAction("GetAppointments");
          // return View("~/Views/Doctor/DoctorViewAppointments.cshtml", appointments);
        }

        public ActionResult cancelAllAppointmentByDate()
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            Doctor_Api doctorApi = new Doctor_Api();
            AppointmentModel app = new AppointmentModel();
            //app.appointment_ID = id;
            app.appointment_Date = Convert.ToDateTime(TempData["Date"].ToString());
            app.doctor_ID = (int)Session["UserId"];
            var appointments = doctorApi.cancelAllAppointmentByDate(app);

            return RedirectToAction("GetAppointments");
            //return View("~/Views/Doctor/DoctorViewAppointments.cshtml", appointments);
        }

        public ActionResult GetReports()
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            return View("~/Views/Doctor/DoctorManageReports.cshtml");
        }

        public ActionResult ViewAllReportsByDoctor()
        {
            if (Convert.ToString(Session["key"]) != "doctor") return RedirectToAction("Login", "Home");

            Patient_Api patientApi = new Patient_Api();
            ViewBag.GetPatientsList = new SelectList(patientApi.GetPaitentsList());

            LabIncharge_Api inchargeApi = new LabIncharge_Api();
            var reportsModel = inchargeApi.GetAllPatientReports_Api();

            return View("~/Views/Doctor/DoctorManageReports.cshtml", reportsModel);
        }

        public ActionResult ViewPatients()
        {
            Admin_Api adminApi = new Admin_Api();
            var pats = adminApi.GetAllPatients();
            AppointmentModel docapts = new AppointmentModel();

            foreach (var d in pats)
            {
                docapts.dropDown.Add(new SelectListItem
                {
                    Text = d.firstName,
                    Value = Convert.ToString(d.pid)
                });
            }
            return View("~/Views/Doctor/ViewPatientList.cshtml",docapts);
        }


        public ActionResult ViewReportsByPatient(AppointmentModel app)

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorAddReport.cshtml
@model Models.ReportModel

@*@{
    ViewBag.Title = "DoctorAddReport";
}*@

@section ContentBreadCrumBar
    {
    <a class="glyphicon "> Doctor Add Report</a>
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="karthik" content="">
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script>

    var $j = jQuery.noConflict();
    $j(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $j('.date-picker').datepicker();
    });
    </script>
    <style>
        table#detailsTable {
            width: 60% !important;
        }
    </style>


</head>
<body>

  
    @using (Html.BeginForm("CreateReport", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
    {
        <table border="1" id="detailsTable" style="width:100%">
            <thead>
                <tr>
                    <th>Select Patient</th>
                    <th>Report Generated Time</th>
                    <th style="">Date</th>
                    <th>Lab Result</th>
                </tr>
            </thead>
                <tr style="text-align:center">
                    <td>
                       @Html.DropDownListFor(i => i.patient_ID, (SelectList)ViewBag.GetPatientsList, "--Select--")
                    </td>
                    <td>
                        @Html.DropDownListFor(i => i.reportTime, new List<SelectListItem> {
                                   new SelectListItem{ Value="-Select", Text="-Select-"},
                               new SelectListItem{ Value="09:00", Text="09:00"},
                               new SelectListItem{ Value="10:00", Text="10:00"},
                               new SelectListItem{ Value="11:00", Text="11:00"},
                               new SelectListItem{ Value="12:00", Text="12:00"},
                               new SelectListItem{ Value="13:00", Text="13:00"}})
                    </td>
                    <td>
                        @Html.TextBoxFor(i => i.date, "", new { @class = "date-picker" })
                    </td>
                    <td>
                        @Html.TextAreaFor(i => i.labResult)
                    </td>
                </tr>
        </table>
        <input type="submit" value="Submit Report" class="btn btn-info btn-block">
    }
    

</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorBookAppointment.cshtml
@model Models.AppointmentModel
@{
    ViewBag.Title = "DoctorBookAppointment";
}

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function ()
        {
            $j('.date-picker').datepicker({

                defaultDate: "+1w",
                //defaultDate: new Date(),
                changeMonth: true,
                numberOfMonths: 1,
                minDate : 1,
                maxDate : "+3Y",
             


                onSelect:function(dateText,instance){
                    var d = dateText.toString();
                    console.log($("#PatientName").val());
                    aaappModel =
                        {
                            'appointment_Date': dateText,
                            'paitent_ID': $("#PatientName").val()
                    }

                    $.ajax({
                        type: "POST",
                        url: "GetAvailableTimings",


                        data: JSON.stringify(aaappModel),//"{ 'text':'" + d + "'}",
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function(data)
                        {
                            $("#timingsDropDown").empty();
                          //  console.log(data);
                            $.each(data, function (i, obj) {
                                if (obj.Text == "00:00") {
                                    alert("Appointment Already Booked for this Date, check appointments");
                                    return;
                                }
                                var p = new Option(obj.Text, obj.Value);
                                $("#timingsDropDown").append(p);
                            });
                        }
                    });
                }
            });
        });

    </script>
    <style>
        th.ui-datepicker-week-end,
        td.ui-datepicker-week-end {
            display: none;
        }
    </style>
</head>
<body>
    @section ContentBreadCrumBar
    {
        <a class="glyphicon glyphicon-home"> Doctor Book Appointment</a>
    }
 
        <table id="detailsTable">
                <thead>
                    <tr>
                        <th>Patient Name </th>
                        <th>Appointment Date</th>
                        <th>Appointment Time</th>
                        <th>Action</th>
                    </tr>
                </thead>
                        @using (Html.BeginForm("BookNewAppointment", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
                        {
                           
                                <tr>
                                    <td>@Html.DropDownListFor(i => i.paitent_ID, new SelectList(Model.dropDown,"Value","Text"), "Select Patient", new { @id = "PatientName" })</td>
                                    <td>
                                        @Html.TextBoxFor(i => i.appointment_Date, "", new { @class = "date-picker"  })
                                    </td>
                                    <td>
                                        @Html.DropDownListFor(i=> i.timings, Enumerable.Empty<SelectListItem>(), "-Select Timing-", new { @id="timingsDropDown"})
                                    </td>
                                    <td><input type="submit" value="Book Appointment" /></td>
                                </tr>
                        }
            </table>
  
    
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorCancelAppts.cshtml
@{
    ViewBag.Title = "Doctor Cancel Appointments";
}

<h5>Doctor Cancel Appointments</h5>

@model IEnumerable<Models.AppointmentModel>

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function () {
            $j('.date-picker').datepicker({

                    defaultDate: "+1w",
                //defaultDate: new Date(),
                    defaultDate: new Date($(this).val().slice(-4), $(this).val().substring(0, 2), 1),
                    changeMonth: true,
                    numberOfMonths: 1,
                    minDate: 0,
                    maxDate: "+3Y",
                    startDate: new Date($(this).val().slice(-4), $(this).val().substring(0, 2), 1),



                    @*onSelect: function (dateText, instance) {
                        var d = dateText.toString();
                        var PatDocId = $('#doctor :selected').val();

                        console.log(PatDocId);
                        var apmtModel =
                            {
                                "patient_Id": 0,
                                "timings": d,
                                "doctor_ID": PatDocId
                            };


                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetAvailableTimings", "Doctor")' ,// "GetAvailableTimings",
                            data: JSON.stringify(apmtModel),
                            contentType: "application/json; charset=utf-8",
                           // dataType: "json",
                            success: function (data) {
                                $("#timingsDropDown").empty();
                                $.each(data, function (i, obj) {
                                    var p = new Option(obj.Text, obj.Value);
                                    $("#timingsDropDown").append(p);
                                });
                            }
                        });
                    }*@
                }

                );
        });
    </script>


</head>
<body>
    @section ContentBreadCrumBar
{
        <a class="glyphicon glyphicon-home"> Doctor Cancel Appointments</a>
    }


    <table>
        <tr>

            @using (Html.BeginForm("GetAppointmentsByDate", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
            {
                <td>@Html.TextBox("test", "", new { @Class = "date-picker" })</td>
                <td><input type="submit" value="Select All Appointments" /></td>
                @*<td><input type="submit" value="Cancel All Appointments" /></td>*@

            }
        </tr>
    </table>

    <br/>
    <br />


    <table border="1" id="detailsTable" style="width:100%">
        <thead>
            <tr>
                <th>Appointment Number</th>
                <th>Patient </th>
                <th>Appointment Date</th>
                <th>Appointment Time</th>
            </tr>
        </thead>
        @foreach (var apmnt in Model)
        {
            <tr style="text-align:center">
                <td>
                    @apmnt.appointment_ID
                </td>
                <td>
                    @apmnt.patientName
                </td>
                <td>
                    @((apmnt.appointment_Date).ToShortDateString())
                </td>
                <td>
                    @apmnt.timings
                </td>
                
            </tr>
        }
    </table>

    <table>
        <tr>

            @using (Html.BeginForm("cancelAllAppointmentByDate", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
            {
                <td>@Html.Hidden("test", "", new { @Class = "date-picker" })</td>
                <td><input type="submit" value="Cancel All Appointments" /></td>
            }
        </tr>
    </table>

</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorFilterAppointments.cshtml
@{
    ViewBag.Title = "DoctorFilterAppointments";
}
@model IEnumerable<Models.AppointmentModel>

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $j('.date-picker').datepicker();
        });


        function filterAppointmets()
        {
            var selected = $("#filterDropdown option:selected").val();
            console.log(selected);
            if (selected != 0) {
                $.ajax({
                    url: '/Doctor/GetAppointmentsByFilter?id=' + selected,
                    //data: JSON.stringify(selected),
                    //data:{ "id" :selected},
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    //success: function () {
                    //    location.reload();
                    //}
                });
            }
        }

    </script>

</head>
<body>
    @section ContentBreadCrumBar
    {
        <a class="glyphicon glyphicon-home"> Doctor manage Appointments</a>
    }
    <select onchange="filterAppointmets()" onclick="" id="filterDropdown">
        <option value="0">-Select-</option>
        <option value="1">Today</option>
        <option value="2">Tomorrow</option>
        <option value="3" selected>All</option>
    </select>

    <table border="1" id="detailsTable" style="width:100%">
        <thead>
            <tr>
                <th>Appointment Number</th>
                <th>Patient </th>
                <th>Appointment Date</th>
                <th>Appointment Time</th>
                <th>Cancel</th>
                <th>View Report</th>
            </tr>
        </thead>
        @foreach (var apmnt in Model)
        {
            <tr style="text-align:center">
                <td>
                    @apmnt.appointment_ID
                </td>
                <td>
                    @apmnt.patientName
                </td>
                <td>
                    @((apmnt.appointment_Date).ToShortDateString())
                </td>
                <td>
                    @apmnt.timings
                </td>
                <td>
                    @if (apmnt.canCancel)
                    {
                        @Html.ActionLink("Cancel Appointment", "cancelAppointment", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-warning edit-mode" })
                    }
                </td>
                @* <td>

                        @if (!apmnt.requestedReport)
                        {
                            @Html.ActionLink("Req Report", "ReqReport", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-info edit-mode", data_toggle="modal", data_target= "#exampleModal" })
                        }
                    </td>*@
                <td>
                    @if (apmnt.reportAvailable)
                    {
                        @Html.ActionLink("View Report", "ViewReportsWithID", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-success edit-mode" })
                    }
                </td>
            </tr>
        }
    </table>

    <input type="button" value="Book Appointment" onclick="@("window.location.href='" + @Url.Action("BookNewAppointment", "Doctor" ) +"'");" />

</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorHome.cshtml
@{
    ViewBag.Title = "Doctor Home";
}

@section ContentBreadCrumBar
{
    Doctor Home
}

@*@model IEnumerable<Models.NotificationsModel>*@

@*@if (Model != null)
{
    <div>
        @Html.Partial("_NotificationHome", Model)
    </div>
}*@

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/DoctorViewAppointments.cshtml
@model IEnumerable<Models.AppointmentModel>
@{
    ViewBag.Title = "Doctor Appointments";
}
<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">

        var $j = jQuery.noConflict();
        $j(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $j('.date-picker').datepicker();
        });


        function filterAppointmets()
        {
            var selected = $("#filterDropdown option:selected").val();
            console.log(selected);
            if (selected != 0) {
                $.ajax({
                    url: '/Doctor/GetAppointmentsByFilter?id=' + selected,
                    //data: JSON.stringify(selected),
                    //data:{ "id" :selected},
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    //success: function () {
                    //    location.reload();
                    //}
                });
            }
        }

    </script>
  
</head>
<body>
    @section ContentBreadCrumBar
    {
        <a class="glyphicon glyphicon-home"> Doctor manage Appointments</a>
    }
    @*<select onchange="filterAppointmets()" onclick="" id="filterDropdown">
        <option value="0">-Select-</option>
        <option value="1">Today</option>
        <option value="2">Tomorrow</option>
        <option value="3" selected>All</option>
    </select>*@
@if (Model.Count() > 0)
{


using (Html.BeginForm("GetAppointmentsByFilter", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
{
    @Html.DropDownListFor(m => m.First().filterID, new SelectList(Model.First().filterApps, "Value", "Text"))
    <button type="submit" value="Submit">Submit</button>
}
}
    <table border="1" id="detailsTable" style="width:100%">
        <thead>
            <tr>
                <th>Appointment Number</th>
                <th>Patient </th>
                <th>Appointment Date</th>
                <th>Appointment Time</th>
                <th>Cancel</th>
                <th>View Report</th>
            </tr>
        </thead>
        @foreach (var apmnt in Model)
        {
            <tr style="text-align:center">
                <td>
                    @apmnt.appointment_ID
                </td>
                <td>
                    @apmnt.patientName
                </td>
                <td>
                    @((apmnt.appointment_Date).ToShortDateString())
                </td>
                <td>
                    @apmnt.timings
                </td>
                <td>
                    @if (apmnt.canCancel)
                    {
                       @Html.ActionLink("Cancel Appointment", "cancelAppointment", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-warning edit-mode" })
                    }
                </td>
                @* <td>
                   
                    @if (!apmnt.requestedReport)
                    {
                        @Html.ActionLink("Req Report", "ReqReport", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-info edit-mode", data_toggle="modal", data_target= "#exampleModal" })
                    }
                </td>*@
                <td>
                    @if(apmnt.reportAvailable)
                    {
                    @Html.ActionLink("View Report", "ViewReportsWithID", "Doctor", new { id = @apmnt.appointment_ID }, new { @Class = "btn btn-success edit-mode" })
                    }
                </td>
            </tr>
        }
    </table>

    <input type="button"  value="Book Appointment" onclick="@("window.location.href='" + @Url.Action("BookNewAppointment", "Doctor" ) +"'");"/>
  
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/ReportAvailability.cshtml
@{
    ViewBag.Title = "Report Availability";
}

<h4 style="text-align: center; padding-top:5%;">Report not yet generated for this Appointment</h4>

<input type="button" value="View Appointments" style="align-content:center" onclick="@("window.location.href='" + @Url.Action("GetAppointments", "Doctor" ) +"'");" />

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Doctor/ViewPatientList.cshtml
@{
    ViewBag.Title = "View Patient List";
}

@model Models.AppointmentModel


<h3>Select Patient</h3>

<table>
    <tr>
        @using (Html.BeginForm("ViewReportsByPatient", "Doctor", FormMethod.Post, new { enctype = "multipart/form" }))
        {
            <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.paitent_ID, new SelectList(Model.dropDown, "Value", "Text"), "--Select--")</td>

            <td><input type="submit" value="Submit" /></td>
        }
    </tr>
</table>