HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/EmailsController.cs
using System;
using System.Web.Mvc;
using Models;
using Client_Api;
using System.Net.Mail;
using System.Collections.Generic;
using System.Linq;

namespace HospitalManagmentSystemClient.Controllers
{
    public class EmailsController : Controller
    {
        // GET: Email
        public ActionResult SendEmail()
        {
            return View();
        }


        public ActionResult SendEmailToPpl(EmailModel Model)
        {
            try
            {
                MailMessage mailMessage = new MailMessage("karthikaspdotnet@gmail.com", Model.ToEmail);
                // Specify the email body
                mailMessage.Body = Model.EMailBody;
                mailMessage.Subject = Model.EmailSubject;
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
                smtpClient.Credentials = new System.Net.NetworkCredential()
                {
                    UserName = "karthikaspdotnet@gmail.com",
                    Password = "karthik*123"
                };
                smtpClient.EnableSsl = true;
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {
                Utils.Logging(ex, 2);
            }
            ViewBag.SuccessEmail = "SuccessFully Sent Email";
            return RedirectToAction("SendEmail");//View("~/Views/Emails/SendEmail.cshtml");
        }

        public void SendEmails(string emailTo, string emailBody)
        {
            try
            {
                MailMessage mailMessage = new MailMessage("karthikaspdotnet@gmail.com", emailTo);
                // Specify the email body
                mailMessage.Body = emailBody;
                mailMessage.Subject = "Testing smtp";
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
                smtpClient.Credentials = new System.Net.NetworkCredential()
                {
                    UserName = "karthikaspdotnet@gmail.com",
                    Password = "karthik*123"
                };
                smtpClient.EnableSsl = true;
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {
                Utils.Logging(ex, 2);
            }
        }

        public void EmailToPatients()
        {
            try
            {
                Email_Api emailApi = new Email_Api();
               var patients = emailApi.GetPatientsAppointments();
                foreach (var p in patients)
                {
                    SendEmails(p.emailID,"Dear Patient you have appointment with Doctor");
                }
            }
            catch(Exception ex)
            {
                Utils.Logging(ex, 2);
            }
        }

        public void EmailBooking(AppointmentModel app)
        {
            try
            {
                Email_Api emailApi = new Email_Api();
                Appointment_Api aptms = new Appointment_Api();
                var apppointment = aptms.GetAllAppointments().Where(a => a.appointment_ID == app.appointment_ID).First();
                var patients = emailApi.GetPatientsAppointments();

                Admin_Api adminApi = new Admin_Api();
                var patDetails = (adminApi.GetAllPatients()).Where(p => p.pid == apppointment.paitent_ID).First();

                MailMessage mailMessage = new MailMessage("karthikaspdotnet@gmail.com", patDetails.emailID);
                // Specify the email body
                mailMessage.Body = "Dear Patient you have booked appointment with Doctor " + app.doctorName +
                        " Appointment ID is " + app.appointment_ID + " appointment time is " + app.timings;
                mailMessage.Subject = "Success Booking";
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
                smtpClient.Credentials = new System.Net.NetworkCredential()
                {
                    UserName = "karthikaspdotnet@gmail.com",
                    Password = "karthik*123"
                };
                smtpClient.EnableSsl = true;
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {
                Utils.Logging(ex, 2);
            }
        }

        public void EmailCancelledAppt(AppointmentModel app)
        {
            try
            {
                Email_Api emailApi = new Email_Api();
                Appointment_Api aptms = new Appointment_Api();
                var apppointment = aptms.GetAllAppointments().Where(a => a.appointment_ID == app.appointment_ID).First();
                var patients = emailApi.GetPatientsAppointments();

                Admin_Api adminApi = new Admin_Api();
                var patDetails = (adminApi.GetAllPatients()).Where(p => p.pid == apppointment.paitent_ID).First();

                MailMessage mailMessage = new MailMessage("karthikaspdotnet@gmail.com", patDetails.emailID);
                // Specify the email body
                mailMessage.Body = "Dear Patient youre appointment with Doctor " + apppointment.doctorName +
                        " Appointment ID is " + app.appointment_ID + " appointment time is " + apppointment.timings + "is cancelled kindly reschedule";
                mailMessage.Subject = "Appointment  cancelled ";
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
                smtpClient.Credentials = new System.Net.NetworkCredential()
                {
                    UserName = "karthikaspdotnet@gmail.com",
                    Password = "karthik*123"
                };
                smtpClient.EnableSsl = true;
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {
                Utils.Logging(ex, 2);
            }
        }
        //[HttpPost]
        //public ActionResult SendEmail(EmailModel email)
        //{
        //    try
        //    {
        //        //Configuring webMail class to send emails  
        //        //gmail smtp server  
        //        WebMail.SmtpServer = "smtp.gmail.com";
        //        //gmail port to send emails  
        //        WebMail.SmtpPort = 587;
        //        WebMail.SmtpUseDefaultCredentials = true;
        //        //sending emails with secure protocol  
        //        WebMail.EnableSsl = true;
        //        //EmailId used to send emails from application  
        //        WebMail.UserName = "karthikaspdotnet@gmail.com";
        //        WebMail.Password = "karthik*123";

        //        //Sender email address.  
        //        WebMail.From = "karthikaspdotnet@gmail.com";

        //        //Send email  
        //        WebMail.Send(to: email.ToEmail, subject: email.EmailSubject, body: email.EMailBody, cc: email.EmailCC, bcc: email.EmailBCC, isBodyHtml: true);
        //        ViewBag.Status = "Email Sent Successfully.";
        //    }
        //    catch (Exception ex)
        //    {
        //        Utils.Logging(ex, null);
        //        ViewBag.Status = "Problem while sending email, Please check details.";

        //    }

        //    return View();
        //}


        // [HttpPost]
        //public void SendEmail(EmailModel email)
        //{
        //    try
        //    {
        //        //Configuring webMail class to send emails  
        //        //gmail smtp server  
        //        WebMail.SmtpServer = "smtp.gmail.com";
        //        //gmail port to send emails  
        //        WebMail.SmtpPort = 587;
        //        WebMail.SmtpUseDefaultCredentials = true;
        //        //sending emails with secure protocol  
        //        WebMail.EnableSsl = true;
        //        //EmailId used to send emails from application  
        //        WebMail.UserName = "karthikaspdotnet@gmail.com";
        //        WebMail.Password = "karthik*123";

        //        //Sender email address.  
        //        WebMail.From = "karthikaspdotnet@gmail.com";

        //        //Send email  
        //        WebMail.Send(to: email.ToEmail, subject: email.EmailSubject, body: email.EMailBody, cc: email.EmailCC, bcc: email.EmailBCC, isBodyHtml: true);
        //        ViewBag.Status = "Email Sent Successfully.";
        //    }
        //    catch (Exception ex)
        //    {
        //        Utils.Logging(ex, null);
        //        ViewBag.Status = "Problem while sending email, Please check details.";

        //    }
        //}
    }
}

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Controllers/Nurse/NurseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Client_Api;
using Models;


namespace HospitalManagmentSystemClient.Controllers.Nurse
{
    public class NurseController : Controller
    {
        // GET: Nurse
        public ActionResult Index(int? id)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");
            if (id != null)
            {
                System.Web.HttpContext.Current.Session.Add("key", "nurse");
                System.Web.HttpContext.Current.Session.Add("UserId", id);
                Login_Api la = new Login_Api();
                var name = la.GetUserName(id);

                System.Web.HttpContext.Current.Session.Add("UserName", name);
            }
            Admin_Api adminApi = new Admin_Api();
            NotificationsModel notificationModel = new NotificationsModel();
            notificationModel.UserRoleID = (int)Session["UserId"]; //6003
            var notifications = adminApi.GetAllNotificationsByRole(notificationModel);
            return View("~/Views/Nurse/NurseHome.cshtml", notifications);
        }

        public ActionResult SelectDoctors()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

           AppointmentModel doctorApts = new AppointmentModel();

            Admin_Api adminApi = new Admin_Api();
            var docs = adminApi.GetAllDoctor();

            foreach (var d in docs)
            {
                doctorApts.dropDown.Add(new SelectListItem
                    { Text = d.firstName,
                Value =Convert.ToString(d.pid)});
            }

            return View("~/Views/Nurse/ViewDoctorsList.cshtml", doctorApts);
        } 


        public ActionResult ViewDoctorAppointments(AppointmentModel person)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            Doctor_Api doctorApi = new Doctor_Api();
            if (person.doctor_ID != 0)
            {
                var doctorApmnts = doctorApi.GetDocApntment_Api(person.doctor_ID).Where(a => (a.cancelled == false && a.appointment_Date > DateTime.Now));
                return View("~/Views/Nurse/NurseViewDoctorAppointments.cshtml", doctorApmnts);
            }
            else
            {
                AppointmentModel doctorApts = new AppointmentModel();

                Admin_Api adminApi = new Admin_Api();
                var docs = adminApi.GetAllDoctor();

                foreach (var d in docs)
                {
                    doctorApts.dropDown.Add(new SelectListItem
                    {
                        Text = d.firstName,
                        Value = Convert.ToString(d.pid)
                    });
                }

                return View("~/Views/Nurse/ViewDoctorsList.cshtml", doctorApts);
            }
          }


        public ActionResult SelectPatients()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            Admin_Api adminApi = new Admin_Api();
            var pats = adminApi.GetAllPatients();
            AppointmentModel docapts = new AppointmentModel();

            foreach (var d in pats)
            {
                docapts.dropDown.Add(new SelectListItem
                {
                    Text = d.firstName,
                    Value = Convert.ToString(d.pid)
                });
            }

            return View("~/Views/Nurse/ViewPatientList.cshtml", docapts);
        }

        public ActionResult ViewPatientAppointments(AppointmentModel person)
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");
            Patient_Api patientApi = new Patient_Api();
            var patientApmnts = patientApi.GetAppointments(person.paitent_ID).Where(a => (a.cancelled == false && a.appointment_Date > DateTime.Now));
            return View("~/Views/Nurse/NurseViewPatientAppointments.cshtml", patientApmnts);
        }


        public ActionResult ViewRooms()
        {
            if (Convert.ToString(Session["key"]) != "nurse") return RedirectToAction("Login", "Home");

            TreatmentRoom_Api roomApi = new TreatmentRoom_Api();
            var model = roomApi.GetAllTreatmentRooms();

            Patient_Api patientApi = new Patient_Api();
            var p = patientApi.GetPaitentsList();

            foreach (var m in model)
            {
                m.patientList = p;
            }

            return View("~/Views/Nurse/NurseViewRooms.cshtml", model);
        }
    }
}

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_AdminIndex.cshtml
<div class=".navbar-fixed-left">
    <table style="background-color:#e0c976">
        <tr style="height: 25%">
            <td>
                <table>
                    <tr>
                        <td>
                            @Html.ActionLink("Home", "Index", "Administrator")
                        </td>
                        </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Manage Patients", "ViewPatients", "Administrator")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Manage Doctors", "ViewDoctors", "Administrator")
                        </td>
                    </tr>
                    <tr>
                        <td>
                           @Html.ActionLink("Manage Accounts", "ViewAccounts", "Email")
                        </td>
                    </tr>
                    </table>
                </td>
            </table>
</div>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_DoctorIndex.cshtml
<div class=".navbar-fixed-left">
    <table style="background-color:#e0c976">
        <tr style="height: 25%">
            <td>
                <table>
                    <tr>
                        <td>
                            @Html.ActionLink("Home", "Index", "Doctor")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Book Appointment","BookNewAppointment","Doctor", new Models.AppointmentModel{ })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("View/Edit Appointment", "GetAppointments", "Doctor")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("View Reports", "GetReports", "Doctor")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Send Email", "Index", "Email")
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td></td>
        </tr>
    </table>
</div>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_Layout.cshtml
@{ 
    var userRole = Models.LoginModel.UserRole ;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  HMS</title>
    <link href="~/Scripts/sideNavBar.css" rel="stylesheet" />
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">

    history.pushState(null, null, location.href);
    window.onpopstate = function () {
        history.go(1);
    };


        window.onload = function () {
            debugger;
            display_ct();
        }

        function display_c() {
            var refresh = 1000; // Refresh rate in milli seconds
            mytime = setTimeout('display_ct()', refresh)
        }
        function display_ct() {
            var x = new Date()
            var x1 = x.getMonth() + "/" + x.getDate() + "/" + x.getYear();
            x1 = x1 + " - " + x.getHours() + ":" + x.getMinutes() + ":" + x.getSeconds();
            document.getElementById('time').innerHTML = x1;
        }

     


    </script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="row" style="color:white">
            <div class="col-md-8"><h4 class="col-sm">Hospital Management System</h4></div>
            <div class="col-md-4"><h4 class="col-sm">Logged in UserID: @(((Session["UserId"]).ToString() != null ? (Session["UserId"]) : 0)) / &nbsp; UserName: &nbsp;@(Session["UserName"]) </h4></div>
        </div>
    </div>

    <div class="wrapper">

        <nav id="sidebar">
            <!-- Sidebar Links -->
            @{
                if ((Session["key"]).ToString() == "login")
                {

                    Response.Redirect(Url.Action("Login", "Home"));
                }
                else if((Session["key"]).ToString() == "doctor")
                {
                <ul class="list-unstyled components">
                    <li>
                            @Html.ActionLink("Home", "Index", "Doctor",new { }, new { @class= "glyphicon glyphicon-briefcase" })
                    </li>
                    <li>
                            @Html.ActionLink("Manage Appointments", "GetAppointments", "Doctor", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>
                    <li>
                            @Html.ActionLink(" Manage Reports", "ViewPatients", "Doctor", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>
                    <li>
                           @Html.ActionLink(" Manage Account", "ViewAccountDetails", "Doctor", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>
                    <li>
                          @Html.ActionLink("Book Appointment", "BookNewAppointment", "Doctor")
                    </li>
                    <li>
                        @Html.ActionLink("Request Report", "NewReport", "Doctor")
                    </li>
                    <li>
                        @Html.ActionLink("Cancel Appointments", "ViewAppointmentsToCancel", "Doctor")
                    </li>
                    <li>
                            @Html.ActionLink("Send Email","SendEmail","Emails")
                    </li>
                    <li>
                        @Html.ActionLink("Logout", "SignOutUser", "Home")
                    </li>
                </ul>
            }
          else  if ((Session["key"]).ToString() == "admin")
            {
                <ul class="list-unstyled components">
                    @*<li>
                        @Html.ActionLink(" Home", "Index", "Administrator")
                    </li>*@
                    <li>
                        @Html.ActionLink("Manage Billing", "ViewBilling", "Administrator")
                    </li>
                    <li>
                        @Html.ActionLink("View Payments", "ViewPatientsForPayments", "Administrator")
                    </li>
                    <li>
                        @Html.ActionLink("Pay Payments", "ViewForPayments", "Administrator")
                    </li>
                    <li>
                        @Html.ActionLink("Manage Notifications", "GetAllNotifications", "Administrator")
                    </li>
                    <li>
                        @Html.ActionLink("Manage Rooms", "ViewRooms", "Administrator")
                    </li>
                    <li>
                        @Html.ActionLink("View Rooms", "ViewPatRoomBooking", "Administrator")
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Manage User
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:darkslategray;color:floralwhite">
                            <li>@Html.ActionLink("Manage Doctors", "ViewDoctors", "Administrator", new { } ,new { @style = "color:azure" })</li>
                            <li>@Html.ActionLink("Manage Patients", "ViewPatients", "Administrator", new { @style = "color:azure" })</li>
                            <li>@Html.ActionLink("Manage Nurse", "ViewNurses", "Administrator", new { @style = "color:azure" })</li>
                            <li>@Html.ActionLink("Manage Incharge", "ViewLabIncharges", "Administrator", new { @style = "color:azure" })</li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Send Email", "SendEmail", "Emails")
                    </li>
                    <li>
                        @Html.ActionLink("Logout", "SignOutUser", "Home")
                    </li>
                </ul>
            }
            else if ((Session["key"]).ToString() == "patient")
            {
                <ul class="list-unstyled components">
                    <li>
                        @Html.ActionLink(" Home", "Index", "Patient",new { }, new { @class = "glyphicon glyphicon-home" })
                    </li>
                    <li>
                        @Html.ActionLink(" View/Edit Appointments", "GetAppointments", "Patient", new { }, new { @class = "glyphicon glyphicon-edit" })
                    </li>
                    <li>
                        @Html.ActionLink("Book Appointment", "PatientAppointment", "Patient", new { }, new { @class = "glyphicon glyphicon-th-large" })
                    </li>
                    <li>
                        @Html.ActionLink("View Billing", "ViewBills", "Patient", new { }, new { @class = "glyphicon glyphicon-th-large" })
                    </li>
                    <li>
                        @Html.ActionLink("Pay Payments", "GetPayments", "Patient", new { }, new { @class = "glyphicon glyphicon-envelope" })
                    </li>
                    <li>
                        @Html.ActionLink("View Payments", "PayPayments", "Patient", new { }, new { @class = "glyphicon glyphicon-envelope" })
                    </li>
                    
                    <li>
                        @Html.ActionLink("View Reports", "ViewReports", "Patient", new { }, new { @class = "glyphicon glyphicon-envelope" })
                    </li>
                    <li>
                        @Html.ActionLink(" Manage Account", "ViewManageAccount", "Patient", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>
                    <li >
                       @Html.ActionLink(" Send Email", "SendEmail", "Emails", new { }, new { @class = "glyphicon glyphicon-envelope" })
                    </li>
                    <li>
                        @Html.ActionLink("Logout", "SignOutUser", "Home")
                    </li>
                </ul>
            }
           else if ((Session["key"]).ToString() == "nurse")
            {
                <ul class="list-unstyled components">
                    <li>
                        @Html.ActionLink(" Home", "Index", "Nurse")
                    </li>
                    <li>
                        @Html.ActionLink(" View Doctor Appointments", "SelectDoctors", "Nurse")
                    </li>
                    <li>
                        @Html.ActionLink(" View Patient Appointments", "SelectPatients", "Nurse")
                    </li>
                    <li>
                        @Html.ActionLink(" Check rooms", "ViewRooms", "Nurse")
                    </li>
                    <li>
                        @Html.ActionLink(" Send Email", "SendEmail", "Emails")
                    </li>
                    @*<li>
                        @Html.ActionLink(" Manage Account", "", "", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>*@
                    <li>
                        @Html.ActionLink("Logout", "SignOutUser", "Home")
                    </li>
                </ul>
            }
           else if ((Session["key"]).ToString() == "labIncharge")
            {
                <ul class="list-unstyled components">
                    <li>
                        @Html.ActionLink(" Home", "Index", "LabIncharge")
                    </li>
                    <li>
                        @Html.ActionLink(" View Reports", "ViewPatientReports", "LabIncharge")
                    </li>
                    <li>
                        @Html.ActionLink(" Create Reports", "ViewCreateNewReport", "LabIncharge")
                    </li>
                    <li>
                        @Html.ActionLink(" Send Email", "SendEmail", "Emails")
                    </li>
                    @*<li>
                        @Html.ActionLink(" Manage Account", "", "", new { }, htmlAttributes: new { @class = "glyphicon glyphicon-briefcase" })
                    </li>*@
                    <li>
                        @Html.ActionLink("Logout", "SignOutUser", "Home")
                    </li>
                </ul>
            }
            }
        </nav>

        <div style="width:100%;">
            <div class="pull-right">
                <div class="breadcrumb" > @RenderSection("ContentBreadCrumBar", false) </div>
            </div>
           
            
            <button type="button" id="sidebarCollapse" class="btn btn-outline-primary">
                <i class="glyphicon glyphicon-align-left"></i>
                Toggle 
            </button>
                @RenderBody()
        </div>
        
    </div>

    
    <div class="footer text-center navbar-fixed-bottom" style="height:7%">

        Copyright: <a href="http://karthiknanchari.com/"> &copy; Karthik Nanchari  @DateTime.Now.Year </a>

    </div>

    <script >
        window.onload = function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_LoginLayout.cshtml
@{
    ViewBag.Title = "Login";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  HMS</title>
    <link href="~/Scripts/sideNavBar.css" rel="stylesheet" />
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">

    history.pushState(null, null, location.href);
    window.onpopstate = function () {
        history.go(1);
    };


        window.onload = function () {
            debugger;
            display_ct();
        }

        function display_c() {
            var refresh = 1000; // Refresh rate in milli seconds
            mytime = setTimeout('display_ct()', refresh)
        }
        function display_ct() {
            var x = new Date()
            var x1 = x.getMonth() + "/" + x.getDate() + "/" + x.getYear();
            x1 = x1 + " - " + x.getHours() + ":" + x.getMinutes() + ":" + x.getSeconds();
            document.getElementById('time').innerHTML = x1;
        }




    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-collapse collapse">
        </div>
       
    </div>
            <div>
                @RenderBody()
            </div>

    <div class="footer text-center navbar-fixed-bottom" style="height:7%">

        Copyright: <a href="http://karthiknanchari.com/"> &copy; Karthik Nanchari  @DateTime.Now.Year </a>

    </div>

    <script>
        window.onload = function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_NotificationHome.cshtml
@model IEnumerable<Models.NotificationsModel>
@{
    ViewBag.Title = "_NotificationHome";
}

<!Doctype Html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <link href="~/Scripts/tableStyle.css" rel="stylesheet" />

    <script type="text/javascript">       
    </script>
</head>
<body>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Notificaiton ID</th>
                <th scope="col">User ID</th>
                <th scope="col">Notification</th>
                <th scope="col">Generated Date</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var n in Model)
            {
                <tr>
                    <th scope="row">@n.ID</th>
                    <td>@n.UserRoleID</td>
                    <td>@n.Notifications</td>
                    <td>@n.Created_DateTime</td>
                </tr>
            }

        </tbody>
    </table>
</body>
</html>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_NurseDoctor.cshtml
@model Models.DoctorModel
@{
    ViewBag.Title = "NurseDoctor";
}

<h3>Nurse Select Doctor</h3>

<table>
    <tr>
        @using (Html.BeginForm("ViewDoctorAppointments", "Nurse", FormMethod.Post, new { enctype = "multipart/form" }))
        {
            <td>&nbsp;&nbsp;@Html.DropDownListFor(i =>i.pid, new SelectList(Model.dropDownDoc,"Value","Text"), "--Select--")</td>

                    <td><input type="submit" value="Submit" /></td>
        }
    </tr>
</table>

HospitalManagmentSystemClient/HospitalManagmentSystemClient/Views/Shared/_NursePatient.cshtml
@model Models.PatientModel
@{
    ViewBag.Title = "_NursePatient";
}


<table>
    <tr>
        @using (Html.BeginForm("ViewPatientAppointments", "Nurse", FormMethod.Post, new { enctype = "multipart/form" }))
        {
            <td>&nbsp;&nbsp;@Html.DropDownListFor(i => i.pid, (SelectList)ViewBag.GetPatientsList, "--Select--")</td>

            <td><input type="submit" value="Submit" /></td>
        }
    </tr>
</table>